
"""
ASEO Generated Module

Automatically generated by ASEO Coding Agent.
"""



from fastapi import FastAPI



app = FastAPI()



@app.get("/")

def home():

    return {

        "message":

        "ASEO Generated API"

    }

