services:

  postgres:
    image: postgres:16
    container_name: aseo_postgres
    restart: always

    environment:
      POSTGRES_USER: aseo
      POSTGRES_PASSWORD: aseo_password
      POSTGRES_DB: aseo_db

    ports:
      - "5433:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data


volumes:

  postgres_data: