
"""
ASEO Generated Module

Automatically generated by ASEO Coding Agent.
"""

from app.models.evolution_memory import EvolutionMemory


class EvolutionMemoryRepository:


    def __init__(self, db):

        self.db = db



    def save_feedback(
        self,
        architecture,
        recommendation,
        success
    ):


        memory = (

            self.db.query(
                EvolutionMemory
            )
            .filter(
                EvolutionMemory.architecture == architecture,
                EvolutionMemory.recommendation == recommendation
            )
            .first()

        )


        if not memory:


            memory = EvolutionMemory(

                architecture=architecture,

                recommendation=recommendation,

                usage_count=0,

                successful_count=0

            )


            self.db.add(memory)



        memory.usage_count += 1


        if success:

            memory.successful_count += 1



        memory.success_rate = (

            memory.successful_count /

            memory.usage_count

        )



        memory.confidence = (

            memory.success_rate *

            0.9

        )


        self.db.commit()

        self.db.refresh(memory)


        return memory


    def get_recommendation(
        self,
        recommendation
    ):

        memory = (
            self.db.query(
                EvolutionMemory
            )
            .filter(
                EvolutionMemory.recommendation ==
                recommendation
            )
            .first()
        )


        if memory:
            return memory


        keywords = recommendation.split()


        query = (
            self.db.query(
                EvolutionMemory
            )
        )


        for word in keywords[:2]:

            query = query.filter(
                EvolutionMemory.recommendation.ilike(
                    f"%{word}%"
                )
            )


        return query.first()