
"""
ASEO Generated Module

Automatically generated by ASEO Coding Agent.
"""

from datetime import datetime

from sqlalchemy.orm import Session

from app.models.execution_record import ExecutionRecord
from app.models.project import Project


class ExecutionRepository:


    # =====================================================
    # Create Execution
    # =====================================================

    def create(

        self,

        db: Session,

        project_id: int,

        request: str,

        team: dict | None = None,

        software: dict | None = None,

        deployment: dict | None = None,

        operations: dict | None = None,

        status: str = "QUEUED"

    ):


        execution = ExecutionRecord(

            project_id=project_id,

            request=request,

            team=team,

            software=software,

            deployment=deployment,

            operations=operations,

            status=status

        )


        db.add(execution)

        # Keep transaction control
        # inside Service layer

        db.flush()


        return execution



    # =====================================================
    # Get By ID
    # =====================================================

    def get_by_id(

        self,

        db: Session,

        execution_id: int,

        organization_id: int

    ):


        return (

            db.query(ExecutionRecord)

            .join(

                Project,

                ExecutionRecord.project_id == Project.id

            )

            .filter(

                ExecutionRecord.id == execution_id,

                Project.organization_id == organization_id

            )

            .first()

        )



    # =====================================================
    # Get Project Executions
    # =====================================================

    def get_by_project(

        self,

        db: Session,

        project_id: int,

        organization_id: int

    ):


        return (

            db.query(ExecutionRecord)

            .join(

                Project,

                ExecutionRecord.project_id == Project.id

            )

            .filter(

                ExecutionRecord.project_id == project_id,

                Project.organization_id == organization_id

            )

            .all()

        )

    # =====================================================
    # Get Organization Executions
    # =====================================================

    def get_all_by_organization(

        self,

        db: Session,

        organization_id: int

    ):


        return (

            db.query(ExecutionRecord)

            .join(

                Project,

                ExecutionRecord.project_id == Project.id

            )

            .filter(

                Project.organization_id == organization_id

            )

            .order_by(

                ExecutionRecord.created_at.desc()

            )

            .all()

        )

    # =====================================================
    # Update Status
    # =====================================================

    def update_status(

        self,

        db: Session,

        execution_id: int,

        organization_id: int,

        status: str

    ):


        execution = self.get_by_id(

            db,

            execution_id,

            organization_id

        )


        if not execution:

            return None



        execution.status = status



        if status == "RUNNING":

            execution.started_at = datetime.utcnow()



        if status in [

            "SUCCESS",

            "FAILED"

        ]:

            execution.finished_at = datetime.utcnow()



        db.flush()


        return execution