from datetime import datetime


from sqlalchemy import (
    String,
    DateTime,
    JSON,
    ForeignKey,
    Text
)


from sqlalchemy.orm import (
    Mapped,
    mapped_column,
    relationship
)


from sqlalchemy.sql import func


from app.database.base import Base



class Artifact(Base):

    """
    Persistent execution artifact.

    Stores outputs generated by ASEO agents
    during autonomous execution.
    """


    __tablename__ = "artifacts"



    id: Mapped[int] = mapped_column(

        primary_key=True,

        index=True

    )



    execution_id: Mapped[int] = mapped_column(

        ForeignKey(
            "execution_records.id"
        ),

        nullable=False,

        index=True

    )



    created_by_agent: Mapped[str] = mapped_column(

        String(100),

        nullable=False

    )



    artifact_type: Mapped[str] = mapped_column(

        String(100),

        nullable=False

    )



    name: Mapped[str] = mapped_column(

        String(200),

        nullable=False

    )



    content: Mapped[dict | None] = mapped_column(

        JSON,

        nullable=True

    )



    extra_data: Mapped[dict | None] = mapped_column(

        JSON,

        nullable=True

    )



    created_at: Mapped[datetime] = mapped_column(

        DateTime(timezone=True),

        server_default=func.now()

    )



    execution = relationship(

        "ExecutionRecord",

        back_populates="artifacts"

    )