
"""
ASEO Generated Module

Automatically generated by ASEO Coding Agent.
"""

from sqlalchemy import Column, Integer, String, Float, Boolean
from app.database.base import Base


class EvolutionMemory(Base):

    __tablename__ = "evolution_memory"


    id = Column(
        Integer,
        primary_key=True,
        index=True
    )


    architecture = Column(
        String,
        nullable=False
    )


    recommendation = Column(
        String,
        nullable=False
    )


    success_rate = Column(
        Float,
        default=0
    )


    confidence = Column(
        Float,
        default=0
    )


    usage_count = Column(
        Integer,
        default=0
    )


    successful_count = Column(
        Integer,
        default=0
    )