
"""
ASEO Generated Module

Automatically generated by ASEO Coding Agent.
"""

from sqlalchemy import Column, Integer, String, Text

from app.database.base import Base


class Permission(Base):

    __tablename__ = "permissions"

    id = Column(
        Integer,
        primary_key=True,
        index=True
    )

    name = Column(
        String(100),
        unique=True,
        nullable=False
    )

    description = Column(
        Text,
        nullable=True
    )