
"""
ASEO Generated Module

Automatically generated by ASEO Coding Agent.
"""

from sqlalchemy import Column, Integer, String, ForeignKey

from app.database.base import Base


class RolePermission(Base):

    __tablename__ = "role_permissions"


    id = Column(
        Integer,
        primary_key=True,
        index=True
    )


    role = Column(
        String(50),
        nullable=False
    )


    permission_id = Column(
        Integer,
        ForeignKey(
            "permissions.id",
            ondelete="CASCADE"
        ),
        nullable=False
    )