
"""
ASEO Generated Module

Automatically generated by ASEO Coding Agent.
"""

from app.intelligence.evolution.evolution_rules import (
    ArchitectureEvolutionRules
)

from app.intelligence.evolution.evolution_result import (
    EvolutionResult
)

from app.intelligence.self_improvement.evolution_learning_engine import (
    EvolutionLearningEngine
)


class ArchitectureEvolutionEngine:


    def __init__(
        self,
        db=None
    ):


        self.rules = (
            ArchitectureEvolutionRules()
        )


        self.learning_engine = None

        self.last_learning_results = {}


        if db:

            self.learning_engine = (
                EvolutionLearningEngine(
                    db
                )
            )



    def get_learning_results(
        self,
        recommendations: dict
    ):


        learning_results = {}


        if not self.learning_engine:

            return learning_results



        for key, memory_key in recommendations.items():


            result = (
                self.learning_engine
                .analyze_recommendation(
                    memory_key
                )
            )


            learning_results[key] = {


                "memory_key":
                    memory_key,


                "weight":
                    result.get(
                        "confidence",
                        0
                    ),


                "success_rate":
                    result.get(
                        "success_rate",
                        0
                    ),


                "confidence":
                    result.get(
                        "confidence",
                        0
                    )

            }



        return learning_results



    def calculate_evolution_score(
        self,
        learning_results: dict
    ):


        if not learning_results:

            return 1.0



        scores = []


        for item in learning_results.values():


            success_rate = item.get(
                "success_rate",
                0
            )


            scores.append(
                success_rate
            )



        if not scores:

            return 1.0



        return round(
            sum(scores) / len(scores),
            2
        )





    def evolve(
        self,
        architecture: dict,
        learning_results: dict | None = None
    ):



        if isinstance(
            learning_results,
            list
        ):


            learning_results = None




        if learning_results is None:


            possible_recommendations = {

                "Add Cloud Functions for advanced backend logic":

                    "Add Cloud Functions",


                "Consider PostgreSQL for complex relational data":

                    "Consider PostgreSQL",


                "Use FastAPI Enterprise":

                    "Use FastAPI Enterprise",


                "Use Node Mongo Stack":

                    "Use Node Mongo Stack"

            }



            learning_results = (
                self.get_learning_results(
                    possible_recommendations
                )
            )

            self.last_learning_results = learning_results



            evolution_score = (
                self.calculate_evolution_score(
                    learning_results
                )
            )



        result = self.rules.analyze(

            architecture,

            learning_results

        )



        name = (

            architecture

            .get(
                "backend",
                {}
            )

            .get(
                "technology"
            )

        )



        recommendations = (

            result.get(
                "recommendations",
                []
            )

        )



        improvement_text = []



        for item in recommendations:



            if isinstance(
                item,
                dict
            ):


                recommendation_name = (
                    item.get(
                        "recommendation"
                    )
                )


                memory_data = (
                    learning_results
                    .get(
                        recommendation_name,
                        {}
                    )
                )



                improvement_text.append(

                    {

                        "recommendation":

                            recommendation_name,


                        "weight":

                            item.get(
                                "weight",
                                memory_data.get(
                                    "confidence",
                                    0.5
                                )
                            ),


                        "success_rate":

                            memory_data.get(
                                "success_rate",
                                0
                            ),


                        "confidence":

                            memory_data.get(
                                "confidence",
                                0
                            )

                    }

                )


            else:


                improvement_text.append(

                    {

                        "recommendation":

                            item,


                        "weight":

                            0.5,


                        "success_rate":

                            0,


                        "confidence":

                            0

                    }

                )



        return EvolutionResult(

            architecture=name,


            improvements=

                improvement_text,



            risks=

                result.get(
                    "risks",
                    []
                ),



            future_recommendations=

                improvement_text

        )

    def get_learning_score(
        self,
        architecture
    ):


        if not self.last_learning_results:

            return {

                "success_rate": 0,

                "confidence": 0

            }



        architecture_name = None



        if isinstance(architecture, str):

            architecture_name = architecture



        elif isinstance(architecture, dict):

            backend = (
                architecture
                .get(
                    "backend",
                    {}
                )
            )


            database = (
                architecture
                .get(
                    "database",
                    {}
                )
            )


            deployment = (
                architecture
                .get(
                    "deployment",
                    {}
                )
            )


            architecture_name = " ".join(

                [

                    str(
                        backend.get(
                            "technology",
                            ""
                        )
                    ),

                    str(
                        database.get(
                            "technology",
                            ""
                        )
                    ),

                    str(
                        deployment.get(
                            "technology",
                            ""
                        )
                    )

                ]

            ).lower()



        success_scores = []



        for recommendation, item in self.last_learning_results.items():


            text = recommendation.lower()



            # Firebase matching

            if (
                "firebase" in architecture_name
                and
                (
                    "cloud" in text
                    or
                    "firebase" in text
                )
            ):

                success_scores.append(
                    item.get(
                        "success_rate",
                        0
                    )
                )



            # FastAPI matching

            elif "fastapi" in architecture_name.lower():

                for recommendation, item in self.last_learning_results.items():

                    recommendation_text = recommendation.lower()

                    if "fastapi" in recommendation_text:

                        success_scores.append(
                            item.get(
                                "success_rate",
                                0
                            )
                        )

            
            # Node Mongo matching

            elif "node" in architecture_name.lower():

                for recommendation, item in self.last_learning_results.items():

                    recommendation_text = recommendation.lower()

                    if (
                        "node" in recommendation_text
                        or "mongo" in recommendation_text
                    ):
                        success_scores.append(
                            item.get(
                                "success_rate",
                                0
                            )
                        )

            # PostgreSQL matching

            elif (
                "postgresql" in architecture_name
                and
                "postgresql" in text
            ):

                success_scores.append(
                    item.get(
                        "success_rate",
                        0
                    )
                )



        if not success_scores:

            return {

                "success_rate": 0.5,

                "confidence": 0.5

            }



        score = max(
            success_scores
        )


        return {

            "success_rate":
                round(
                    score,
                    2
                ),


            "confidence":
                round(
                    score,
                    2
                )

        }