
"""
ASEO Generated Module

Automatically generated by ASEO Coding Agent.
"""

from app.intelligence.self_improvement.evolution_feedback import (
    EvolutionFeedback
)

from app.repositories.evolution_memory_repository import (
    EvolutionMemoryRepository
)



class EvolutionLearningEngine:


    def __init__(
        self,
        db
    ):

        self.repository = (
            EvolutionMemoryRepository(
                db
            )
        )



    def record_feedback(
        self,
        feedback: EvolutionFeedback
    ):


        self.repository.save_feedback(

            architecture=
                feedback.architecture,

            recommendation=
                feedback.recommendation,

            success=
                feedback.success

        )


    def analyze_recommendation(
        self,
        recommendation: str
    ):


        memory = (
            self.repository.get_recommendation(
                recommendation
            )
        )


        if not memory:


            # fallback search
            short_name = (
                recommendation
                .replace(
                    " for advanced backend logic",
                    ""
                )
            )


            memory = (
                self.repository.get_recommendation(
                    short_name
                )
            )


        if not memory:

            return {

                "success_rate": 0,

                "confidence": 0

            }


        return {

            "success_rate":

                memory.success_rate,


            "confidence":

                memory.confidence

        }