
"""
ASEO Generated Module

Automatically generated by ASEO Coding Agent.
"""

from dataclasses import dataclass



@dataclass
class EvolutionFeedback:

    architecture: str

    recommendation: str

    success: bool

    impact_score: float = 0.0

    notes: str = ""