
"""
ASEO Generated Module

Automatically generated by ASEO Coding Agent.
"""



from sqlalchemy import Column, Integer, DateTime
from app.database.base import Base
from datetime import datetime


class Appointments(Base):

    __tablename__ = "appointmentss"


    id = Column(
        Integer,
        primary_key=True,
        index=True
    )


    created_at = Column(
        DateTime,
        default=datetime.utcnow
    )


    updated_at = Column(
        DateTime,
        default=datetime.utcnow,
        onupdate=datetime.utcnow
    )

