
"""
ASEO Generated Module

Automatically generated by ASEO Coding Agent.
"""


from fastapi import APIRouter, Depends

from app.services.appointments_service import (
    get_appointmentss,
    create_appointments
)


router = APIRouter(
    prefix="/appointmentss",
    tags=["appointmentss"]
)



@router.get("/")
def list_appointmentss():

    return get_appointmentss()



@router.post("/")
def create_appointments_endpoint(
    data: dict
):

    return create_appointments(
        data
    )
