
"""
ASEO Generated Module

Automatically generated by ASEO Coding Agent.
"""


from fastapi import APIRouter, Depends

from app.services.users_service import (
    get_userss,
    create_users
)


router = APIRouter(
    prefix="/userss",
    tags=["userss"]
)



@router.get("/")
def list_userss():

    return get_userss()



@router.post("/")
def create_users_endpoint(
    data: dict
):

    return create_users(
        data
    )
