
"""
ASEO Generated Module

Automatically generated by ASEO Coding Agent.
"""



from pydantic import BaseModel



class AppointmentsCreate(BaseModel):

    pass



class AppointmentsResponse(BaseModel):

    id: int

