
"""
ASEO Generated Module

Automatically generated by ASEO Coding Agent.
"""



from pydantic import BaseModel



class UsersCreate(BaseModel):

    pass



class UsersResponse(BaseModel):

    id: int

