
"""
ASEO Generated Module

Automatically generated by ASEO Coding Agent.
"""

from datetime import datetime

from pydantic import BaseModel





# ==========================
# Create API Key Request
# ==========================


class APIKeyCreate(BaseModel):

    name: str





# ==========================
# API Key Response
# ==========================


class APIKeyResponse(BaseModel):

    id: int

    name: str

    status: str

    created_at: datetime

    expires_at: datetime | None


    class Config:

        from_attributes = True





# ==========================
# API Key Creation Response
# ==========================


class APIKeyCreateResponse(BaseModel):

    id: int

    api_key: str

    status: str




# ==========================
# API Analytics Response
# ==========================


class APIAnalyticsEndpoint(BaseModel):

    endpoint: str

    count: int





class APIAnalyticsResponse(BaseModel):

    api_key_id: int

    total_requests: int

    today_requests: int

    month_requests: int

    last_request: datetime | None

    top_endpoints: list[APIAnalyticsEndpoint]