
"""
ASEO Generated Module

Automatically generated by ASEO Coding Agent.
"""

from datetime import datetime

from pydantic import BaseModel



class OrganizationCreate(BaseModel):

    name: str

    plan: str = "free"




class OrganizationResponse(BaseModel):

    id: int

    name: str

    plan: str

    created_at: datetime


    class Config:

        from_attributes = True