
"""
ASEO Generated Module

Automatically generated by ASEO Coding Agent.
"""

from datetime import datetime

from pydantic import BaseModel





class ChangePlanRequest(BaseModel):

    plan: str





class SubscriptionResponse(BaseModel):

    id: int

    organization_id: int

    plan: str

    status: str

    started_at: datetime

    expires_at: datetime | None


    class Config:

        from_attributes = True





class PlanLimitsResponse(BaseModel):

    requests_per_minute: int

    requests_per_day: int

    requests_per_month: int





class ChangePlanResponse(BaseModel):

    subscription: SubscriptionResponse

    updated_api_keys: int

    limits: PlanLimitsResponse