class DocumentGenerator:
    """
    ASEO Documentation Generator v1
    """



    def generate_readme(
        self,
        project_name
    ):


        return f"""

# {project_name}


Generated by ASEO AI Engine


## Overview

This project was automatically generated.



## Architecture

Backend:
FastAPI


Database:
PostgreSQL


Authentication:
JWT



## Structure


app/

├── models

├── schemas

├── routes

└── services



## Running


Install dependencies:

pip install -r requirements.txt



Run:

uvicorn app.main:app

"""





    def generate_architecture(self):


        return """

# System Architecture


Client

↓

FastAPI Backend

↓

Services Layer

↓

Database Layer


"""





    def generate_api_docs(self):


        return """

# API Documentation


## Users


GET /users

POST /users


PUT /users/{id}

DELETE /users/{id}



## Appointments


GET /appointments

POST /appointments


"""