
"""
ASEO Generated Module

Automatically generated by ASEO Coding Agent.
"""

from dataclasses import dataclass



@dataclass
class AgentExecutionPlan:

    agents: list

    execution_order: list

    reasons: list