"""
ASEO Generated Module

Automatically generated by ASEO Coding Agent.
"""

from fastapi import (
    APIRouter,
    Depends,
    status,
    HTTPException
)


from sqlalchemy.orm import Session


from app.database.session import (
    get_database
)


from app.security.roles import (
    require_role
)


from app.schemas.api_key import (
    APIKeyCreate,
    APIKeyResponse,
    APIKeyCreateResponse,
    APIAnalyticsResponse
)


from app.services.api_gateway_service import (
    APIGatewayService
)


from app.services.api_analytics_service import (
    APIAnalyticsService
)





router = APIRouter()


service = APIGatewayService()

analytics_service = APIAnalyticsService()





# =====================================================
# Create API Key
# OWNER ONLY
# =====================================================


@router.post(
    "",
    response_model=APIKeyCreateResponse,
    status_code=status.HTTP_201_CREATED,
    summary="Create API Key"
)
def create_api_key(

    data: APIKeyCreate,

    db: Session = Depends(get_database),

    current_user: dict = Depends(
        require_role(
            ["OWNER"]
        )
    )

):


    return service.create_api_key(

        db,

        current_user["organization_id"],

        data.name

    )





# =====================================================
# List Organization API Keys
# OWNER ONLY
# =====================================================


@router.get(
    "",
    response_model=list[APIKeyResponse],
    summary="List Organization API Keys"
)
def list_api_keys(

    db: Session = Depends(get_database),

    current_user: dict = Depends(
        require_role(
            ["OWNER"]
        )
    )

):


    return service.api_key_repository.get_by_organization(

        db,

        current_user["organization_id"]

    )





# =====================================================
# API Key Analytics
# OWNER ONLY
# =====================================================


@router.get(
    "/{api_key_id}/analytics",
    response_model=APIAnalyticsResponse,
    summary="Get API Key Analytics"
)
def get_api_key_analytics(

    api_key_id: int,

    db: Session = Depends(get_database),

    current_user: dict = Depends(
        require_role(
            ["OWNER"]
        )
    )

):


    api_key = service.api_key_repository.get_by_id(

        db,

        api_key_id

    )


    if not api_key:

        raise HTTPException(

            status_code=404,

            detail="API Key not found"

        )


    if api_key.organization_id != current_user["organization_id"]:

        raise HTTPException(

            status_code=403,

            detail="Not allowed"

        )


    return analytics_service.get_api_key_analytics(

        db,

        api_key_id

    )





# =====================================================
# Disable API Key
# OWNER ONLY
# =====================================================


@router.delete(
    "/{api_key_id}",
    summary="Disable API Key"
)
def disable_api_key(

    api_key_id: int,

    db: Session = Depends(get_database),

    current_user: dict = Depends(
        require_role(
            ["OWNER"]
        )
    )

):


    api_key = service.api_key_repository.get_by_id(

        db,

        api_key_id

    )


    if not api_key:

        raise HTTPException(

            status_code=404,

            detail="API Key not found"

        )


    if api_key.organization_id != current_user["organization_id"]:

        raise HTTPException(

            status_code=403,

            detail="Not allowed"

        )


    service.api_key_repository.deactivate(

        db,

        api_key

    )


    return {

        "status": "disabled"

    }





# =====================================================
# Validate API Key
# External API Authentication
# =====================================================


@router.post(
    "/validate",
    summary="Validate API Key"
)
def validate_api_key(

    api_key: str,

    db: Session = Depends(get_database)

):


    key = service.authenticate_api_key(

        db,

        api_key

    )


    if not key:

        raise HTTPException(

            status_code=401,

            detail="Invalid API Key"

        )


    return {

        "authenticated": True,

        "organization_id": key.organization_id

    }





# =====================================================
# Record API Usage
# =====================================================


@router.post(
    "/usage",
    summary="Record API Usage"
)
def record_usage(

    api_key: str,

    endpoint: str,

    db: Session = Depends(get_database)

):


    key = service.authenticate_api_key(

        db,

        api_key

    )


    if not key:

        raise HTTPException(

            status_code=401,

            detail="Invalid API Key"

        )


    rate = service.check_rate_limit(

        db,

        key

    )


    if not rate["allowed"]:

        raise HTTPException(

            status_code=429,

            detail="API rate limit exceeded"

        )



    usage = service.record_usage(

        db,

        key,

        endpoint

    )


    return {

        "status": "tracked",

        "usage_id": usage.id,

        "rate_limit": rate

    }