
"""
ASEO Generated Module

Automatically generated by ASEO Coding Agent.
"""

from fastapi import APIRouter, Depends

from sqlalchemy.orm import Session

from app.database.session import get_database

from app.services.platform_dashboard_service import (
    PlatformDashboardService
)


router = APIRouter()


dashboard_service = PlatformDashboardService()


@router.get(
    "/platform/dashboard"
)
def get_platform_dashboard(

    organization_id: int,

    db: Session = Depends(get_database)

):

    return dashboard_service.get_overview(

        db,

        organization_id

    )