
"""
ASEO Generated Module

Automatically generated by ASEO Coding Agent.
"""

from fastapi import (
    APIRouter,
    Depends
)


from sqlalchemy.orm import Session


from app.database.session import (
    get_database
)


from app.security.roles import (
    require_role
)


from app.schemas.subscription import (
    ChangePlanRequest,
    SubscriptionResponse,
    ChangePlanResponse
)


from app.services.subscription_service import (
    SubscriptionService
)





router = APIRouter()


service = SubscriptionService()





# =====================================================
# Get Current Subscription
# OWNER ONLY
# =====================================================


@router.get(
    "/current",
    response_model=SubscriptionResponse,
    summary="Get Current Subscription"
)
def get_current_subscription(

    db: Session = Depends(get_database),

    current_user: dict = Depends(
        require_role(
            ["OWNER"]
        )
    )

):


    return service.get_subscription(

        db,

        current_user["organization_id"]

    )





# =====================================================
# Change Plan
# OWNER ONLY
# =====================================================


@router.post(
    "/change-plan",
    response_model=ChangePlanResponse,
    summary="Change Subscription Plan"
)
def change_plan(

    data: ChangePlanRequest,

    db: Session = Depends(get_database),

    current_user: dict = Depends(
        require_role(
            ["OWNER"]
        )
    )

):


    result = service.change_plan(

        db,

        current_user["organization_id"],

        data.plan

    )


    return {

        "subscription":

            result["subscription"],


        "updated_api_keys":

            result["updated_api_keys"],


        "limits":

            service.get_plan_limits(

                data.plan

            )

    }