"""add api rate limits table

Revision ID: 0428478c8771
Revises: d370c4d57eb7
Create Date: 2026-08-17 21:18:49.328236

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0428478c8771'
down_revision: Union[str, Sequence[str], None] = 'd370c4d57eb7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_rate_limits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('api_key_id', sa.Integer(), nullable=False),
    sa.Column('requests_per_minute', sa.Integer(), nullable=False),
    sa.Column('requests_per_day', sa.Integer(), nullable=False),
    sa.Column('requests_per_month', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['api_key_id'], ['api_keys.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_api_rate_limits_api_key_id'), 'api_rate_limits', ['api_key_id'], unique=False)
    op.create_index(op.f('ix_api_rate_limits_id'), 'api_rate_limits', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_api_rate_limits_id'), table_name='api_rate_limits')
    op.drop_index(op.f('ix_api_rate_limits_api_key_id'), table_name='api_rate_limits')
    op.drop_table('api_rate_limits')
    # ### end Alembic commands ###
