"""add knowledge relations table

Revision ID: 0de6863745ac
Revises: 85100dfdb24d
Create Date: 2026-08-13 18:17:20.999003

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0de6863745ac'
down_revision: Union[str, Sequence[str], None] = '85100dfdb24d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('knowledge_relations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('target_id', sa.Integer(), nullable=False),
    sa.Column('relation_type', sa.String(length=100), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('usage_count', sa.Integer(), nullable=False),
    sa.Column('extra_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['knowledge_patterns.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_id'], ['knowledge_patterns.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_knowledge_relations_id'), 'knowledge_relations', ['id'], unique=False)
    op.create_index(op.f('ix_knowledge_relations_relation_type'), 'knowledge_relations', ['relation_type'], unique=False)
    op.create_index(op.f('ix_knowledge_relations_source_id'), 'knowledge_relations', ['source_id'], unique=False)
    op.create_index(op.f('ix_knowledge_relations_target_id'), 'knowledge_relations', ['target_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_knowledge_relations_target_id'), table_name='knowledge_relations')
    op.drop_index(op.f('ix_knowledge_relations_source_id'), table_name='knowledge_relations')
    op.drop_index(op.f('ix_knowledge_relations_relation_type'), table_name='knowledge_relations')
    op.drop_index(op.f('ix_knowledge_relations_id'), table_name='knowledge_relations')
    op.drop_table('knowledge_relations')
    # ### end Alembic commands ###
