"""add agent memories table

Revision ID: 21363bbfb706
Revises: ab022757a4e8
Create Date: 2026-08-13 01:38:24.565423

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '21363bbfb706'
down_revision: Union[str, Sequence[str], None] = 'ab022757a4e8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_memories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('agent_name', sa.String(length=100), nullable=False),
    sa.Column('memory_type', sa.String(length=50), nullable=False),
    sa.Column('content', sa.JSON(), nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('organization_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_memories_agent_name'), 'agent_memories', ['agent_name'], unique=False)
    op.create_index(op.f('ix_agent_memories_id'), 'agent_memories', ['id'], unique=False)
    op.create_index(op.f('ix_agent_memories_memory_type'), 'agent_memories', ['memory_type'], unique=False)
    op.create_index(op.f('ix_agent_memories_organization_id'), 'agent_memories', ['organization_id'], unique=False)
    op.create_index(op.f('ix_agent_memories_project_id'), 'agent_memories', ['project_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_agent_memories_project_id'), table_name='agent_memories')
    op.drop_index(op.f('ix_agent_memories_organization_id'), table_name='agent_memories')
    op.drop_index(op.f('ix_agent_memories_memory_type'), table_name='agent_memories')
    op.drop_index(op.f('ix_agent_memories_id'), table_name='agent_memories')
    op.drop_index(op.f('ix_agent_memories_agent_name'), table_name='agent_memories')
    op.drop_table('agent_memories')
    # ### end Alembic commands ###
