"""add decision history

Revision ID: 26be29c71e4a
Revises: 39745c621bbd
Create Date: 2026-08-14 03:25:32.921843

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '26be29c71e4a'
down_revision: Union[str, Sequence[str], None] = '39745c621bbd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('decision_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('architecture', sa.JSON(), nullable=False),
    sa.Column('agents_used', sa.JSON(), nullable=False),
    sa.Column('success_score', sa.Float(), nullable=False),
    sa.Column('extra_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_decision_history_id'), 'decision_history', ['id'], unique=False)
    op.create_index(op.f('ix_decision_history_project_id'), 'decision_history', ['project_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_decision_history_project_id'), table_name='decision_history')
    op.drop_index(op.f('ix_decision_history_id'), table_name='decision_history')
    op.drop_table('decision_history')
    # ### end Alembic commands ###
