"""add cascade delete to project foreign keys

Revision ID: 3203669fd75a
Revises: 2774ba35f0b7
Create Date: 2026-07-31 00:27:34.335328

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3203669fd75a'
down_revision: Union[str, Sequence[str], None] = '2774ba35f0b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_projects_organization'), 'projects', type_='foreignkey')
    op.drop_constraint(op.f('fk_projects_owner'), 'projects', type_='foreignkey')
    op.drop_constraint(op.f('fk_projects_workspace'), 'projects', type_='foreignkey')
    op.create_foreign_key(None, 'projects', 'organizations', ['organization_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'projects', 'users', ['owner_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'projects', 'workspaces', ['workspace_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'projects', type_='foreignkey')
    op.drop_constraint(None, 'projects', type_='foreignkey')
    op.drop_constraint(None, 'projects', type_='foreignkey')
    op.create_foreign_key(op.f('fk_projects_workspace'), 'projects', 'workspaces', ['workspace_id'], ['id'])
    op.create_foreign_key(op.f('fk_projects_owner'), 'projects', 'users', ['owner_id'], ['id'])
    op.create_foreign_key(op.f('fk_projects_organization'), 'projects', 'organizations', ['organization_id'], ['id'])
    # ### end Alembic commands ###
