"""add knowledge pattern context

Revision ID: 39745c621bbd
Revises: 0de6863745ac
Create Date: 2026-08-13 18:46:05.824294

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '39745c621bbd'
down_revision: Union[str, Sequence[str], None] = '0de6863745ac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('knowledge_patterns', sa.Column('context', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('knowledge_patterns', 'context')
    # ### end Alembic commands ###
