"""add knowledge patterns table

Revision ID: 85100dfdb24d
Revises: 3b20c5ec1089
Create Date: 2026-08-13 17:37:27.295483

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '85100dfdb24d'
down_revision: Union[str, Sequence[str], None] = '3b20c5ec1089'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('knowledge_patterns',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('usage_count', sa.Integer(), nullable=False),
    sa.Column('success_rate', sa.Float(), nullable=False),
    sa.Column('extra_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_knowledge_patterns_category'), 'knowledge_patterns', ['category'], unique=False)
    op.create_index(op.f('ix_knowledge_patterns_id'), 'knowledge_patterns', ['id'], unique=False)
    op.create_index(op.f('ix_knowledge_patterns_name'), 'knowledge_patterns', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_knowledge_patterns_name'), table_name='knowledge_patterns')
    op.drop_index(op.f('ix_knowledge_patterns_id'), table_name='knowledge_patterns')
    op.drop_index(op.f('ix_knowledge_patterns_category'), table_name='knowledge_patterns')
    op.drop_table('knowledge_patterns')
    # ### end Alembic commands ###
