"""add project context to decision history

Revision ID: 88c33a2fd498
Revises: 26be29c71e4a
Create Date: 2026-08-14 04:17:01.138840

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '88c33a2fd498'
down_revision: Union[str, Sequence[str], None] = '26be29c71e4a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('decision_history', sa.Column('project_context', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('decision_history', 'project_context')
    # ### end Alembic commands ###
