"""add usage billing table

Revision ID: 95839606e2ca
Revises: e181a83d93af
Create Date: 2026-08-18 03:06:46.367421

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '95839606e2ca'
down_revision: Union[str, Sequence[str], None] = 'e181a83d93af'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usage_billings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('month', sa.String(length=7), nullable=False),
    sa.Column('total_requests', sa.Integer(), nullable=False),
    sa.Column('included_requests', sa.Integer(), nullable=False),
    sa.Column('extra_requests', sa.Integer(), nullable=False),
    sa.Column('cost', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usage_billings_id'), 'usage_billings', ['id'], unique=False)
    op.create_index(op.f('ix_usage_billings_organization_id'), 'usage_billings', ['organization_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_usage_billings_organization_id'), table_name='usage_billings')
    op.drop_index(op.f('ix_usage_billings_id'), table_name='usage_billings')
    op.drop_table('usage_billings')
    # ### end Alembic commands ###
