"""add decision memory table

Revision ID: 9a126a5c1de6
Revises: 663f96127a0e
Create Date: 2026-08-14 17:07:32.364269

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9a126a5c1de6'
down_revision: Union[str, Sequence[str], None] = '663f96127a0e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('decision_memory',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('decision_history_id', sa.Integer(), nullable=True),
    sa.Column('agent_name', sa.String(), nullable=False),
    sa.Column('architecture', sa.JSON(), nullable=False),
    sa.Column('similarity_score', sa.Float(), nullable=False),
    sa.Column('success_score', sa.Float(), nullable=False),
    sa.Column('memory_score', sa.Float(), nullable=False),
    sa.Column('usage_count', sa.Integer(), nullable=False),
    sa.Column('extra_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_decision_memory_decision_history_id'), 'decision_memory', ['decision_history_id'], unique=False)
    op.create_index(op.f('ix_decision_memory_id'), 'decision_memory', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_decision_memory_id'), table_name='decision_memory')
    op.drop_index(op.f('ix_decision_memory_decision_history_id'), table_name='decision_memory')
    op.drop_table('decision_memory')
    # ### end Alembic commands ###
