"""add memory system state table

Revision ID: 9e3158f29ba8
Revises: b8099b12bfac
Create Date: 2026-08-16 02:48:43.231586

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9e3158f29ba8'
down_revision: Union[str, Sequence[str], None] = 'b8099b12bfac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('memory_system_state',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('last_consolidation_count', sa.Integer(), nullable=True),
    sa.Column('total_consolidations', sa.Integer(), nullable=True),
    sa.Column('last_consolidation_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('memory_system_state')
    # ### end Alembic commands ###
