"""add evolution memory table

Revision ID: b8099b12bfac
Revises: d28dde30a23e
Create Date: 2026-08-16 02:32:24.625230

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b8099b12bfac'
down_revision: Union[str, Sequence[str], None] = 'd28dde30a23e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('evolution_memory',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('architecture', sa.String(), nullable=False),
    sa.Column('recommendation', sa.String(), nullable=False),
    sa.Column('success_rate', sa.Float(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('usage_count', sa.Integer(), nullable=True),
    sa.Column('successful_count', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evolution_memory_id'), 'evolution_memory', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_evolution_memory_id'), table_name='evolution_memory')
    op.drop_table('evolution_memory')
    # ### end Alembic commands ###
