"""add cascade delete tasks

Revision ID: d370c4d57eb7
Revises: 373d83cd7683
Create Date: 2026-08-17 20:59:05.189636

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd370c4d57eb7'
down_revision: Union[str, Sequence[str], None] = '373d83cd7683'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('tasks_execution_id_fkey'), 'tasks', type_='foreignkey')
    op.create_foreign_key(None, 'tasks', 'execution_records', ['execution_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.create_foreign_key(op.f('tasks_execution_id_fkey'), 'tasks', 'execution_records', ['execution_id'], ['id'])
    # ### end Alembic commands ###
