
"""
ASEO Generated Module

Automatically generated by ASEO Coding Agent.
"""

import os

from dotenv import load_dotenv

from sqlalchemy import create_engine

from sqlalchemy.orm import sessionmaker

from sqlalchemy.pool import QueuePool



load_dotenv()



DATABASE_USER = os.getenv(
    "DATABASE_USER",
    "aseo"
)


DATABASE_PASSWORD = os.getenv(
    "DATABASE_PASSWORD",
    "aseo_password"
)


DATABASE_HOST = os.getenv(
    "DATABASE_HOST",
    "127.0.0.1"
)


DATABASE_PORT = os.getenv(
    "DATABASE_PORT",
    "5433"
)


DATABASE_NAME = os.getenv(
    "DATABASE_NAME",
    "aseo_db"
)



DATABASE_URL = (
    f"postgresql://{DATABASE_USER}:"
    f"{DATABASE_PASSWORD}@"
    f"{DATABASE_HOST}:"
    f"{DATABASE_PORT}/"
    f"{DATABASE_NAME}"
)





engine = create_engine(

    DATABASE_URL,

    poolclass=QueuePool,

    pool_size=10,

    max_overflow=20,

    pool_pre_ping=True,

    echo=False

)





SessionLocal = sessionmaker(

    autocommit=False,

    autoflush=False,

    bind=engine

)