
"""
ASEO Generated Module

Automatically generated by ASEO Coding Agent.
"""



class AppointmentsService:



    def get_all(self):

        return []



    def create(self, data):

        return data

