
"""
ASEO Generated Module

Automatically generated by ASEO Coding Agent.
"""

from fastapi import Request
from fastapi.responses import JSONResponse



# =====================================
# Base Application Exception
# =====================================

class ASEOException(Exception):

    def __init__(
        self,
        code: str,
        message: str,
        status_code: int = 400
    ):

        self.code = code

        self.message = message

        self.status_code = status_code



        super().__init__(
            message
        )





# =====================================
# Common Exceptions
# =====================================


class NotFoundException(ASEOException):

    def __init__(
        self,
        message="Resource not found"
    ):

        super().__init__(

            code="NOT_FOUND",

            message=message,

            status_code=404

        )





class UnauthorizedException(ASEOException):

    def __init__(
        self,
        message="Unauthorized access"
    ):

        super().__init__(

            code="UNAUTHORIZED",

            message=message,

            status_code=401

        )





class ForbiddenException(ASEOException):

    def __init__(
        self,
        message="Permission denied"
    ):

        super().__init__(

            code="FORBIDDEN",

            message=message,

            status_code=403

        )





class ValidationException(ASEOException):

    def __init__(
        self,
        message="Invalid request"
    ):

        super().__init__(

            code="VALIDATION_ERROR",

            message=message,

            status_code=422

        )





# =====================================
# FastAPI Exception Handler
# =====================================


async def aseo_exception_handler(

    request: Request,

    exc: ASEOException

):


    return JSONResponse(

        status_code=exc.status_code,

        content={

            "success": False,

            "error": {

                "code": exc.code,

                "message": exc.message,

                "request_id":
                    getattr(
                        request.state,
                        "request_id",
                        None
                    )

            }

        }

    )





# =====================================
# Global Exception Handler
# =====================================


async def global_exception_handler(

    request: Request,

    exc: Exception

):


    return JSONResponse(

        status_code=500,

        content={

            "success": False,

            "error": {

                "code": "INTERNAL_ERROR",

                "message":
                    "Internal server error",

                
                "request_id":
                    getattr(
                        request.state,
                        "request_id",
                        None
                    )

                    

            }

        }

    )